In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from scipy import stats as spstats
import numpy as np
import sys
from sklearn.model_selection import StratifiedKFold
import os
import warnings
warnings.filterwarnings('ignore')
sys.path.append("_libs")
from select_features import FC_DimRed
from utils import load_cov_mats, load_atms, load_corr_mats

## 

In [ ]:
while os.getcwd().split(os.sep)[-1] != "REDDI":
    os.chdir("../")
project_root = os.getcwd()  # should be .../REDDI
# src_path = os.path.join(project_root, "v2", "src")
# sys.path.append(src_path)
# sys.path.append(os.path.abspath("../v2/data/features/CovarianceMatrices/OAS/MCI"))

# Load the data
# TODO: selection in cross validation loop !

# Models definition
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

X_atm, y_atm = load_atms(zscore=1.6)
X_atm = X_atm[:, :78, :78]  
dim_red_eta_20_atm = FC_DimRed(eta_threshold=0.1, nb_nodes=20)
X_atm = dim_red_eta_20_atm.fit_transform(X_atm, y_atm, metric='eta-squared')
print(f"Selected nodes ATMs: {dim_red_eta_20_atm.node_select_}")


X_cov_mat, y_cov_mat = load_cov_mats()
X_cov_mat = X_cov_mat[:, :78, :78]
dim_red_eta_50_cov = FC_DimRed(eta_threshold=0.1, nb_nodes=50)
X_cov_mat = dim_red_eta_50_cov.fit_transform(X_cov_mat, y_cov_mat, metric='eta-squared')
print(f"Selected nodes Covariance Matrices: {dim_red_eta_50_cov.node_select_}")


X_corr_mat, y_corr_mat = load_corr_mats()
X_corr_mat = X_corr_mat[:, :78, :78]  
dim_red_eta_20_corr = FC_DimRed(eta_threshold=0.1, nb_nodes=20)
X_corr_mat = dim_red_eta_20_corr.fit_transform(X_corr_mat, y_corr_mat, metric='eta-squared')
print(f"Selected nodes Correlation Matrices: {dim_red_eta_20_corr.node_select_}")


Shape of all data: (109, 116, 116)
Shape of target data: (109,)
Shape of all mapped target data (0, 1, 2, 3): (109,)
Selected nodes ATMs: [36 56 57 63 38 64 49 15 14 54 25 52 65 11  6 17 59  1 42 47]
Shape of all data: (109, 116, 116)
Shape of target data: (109,)
Shape of all mapped target data (0, 1, 2, 3): (109,)
Selected nodes Covariance Matrices: [77 11 73 51 33 26 27 62 50 14 72 67 36 34 18 37 12 44  8  5 71 15 24 31
 39 38 23  9 63 45 76 70 65 40 13  7 17 75  1 25 56 20 59 43 32 21 66 52
 22 60]
Shape of all data: (109, 116, 116)
Shape of target data: (109,)
Shape of all mapped target data (0, 1, 2, 3): (109,)
Selected nodes Correlation Matrices: [77 67 56 20 38 17 51 50 62 12  6 54 75 11 73 18 57 45  7 65]


Previous selection (original code Mario)
Selected nodes Covariance Matrices: [ 1  5  7  8  9 11 12 13 14 15 17 18 20 21 22 23 24 25 26 27 31 32 33 34
 36 37 38 39 40 43 44 45 50 51 52 56 59 60 62 63 65 66 67 70 71 72 73 75
 76 77]
Selected nodes ATMs: [ 1  6 11 14 15 17 25 36 38 42 47 49 52 54 56 57 59 63 64 65]

In [3]:
dim_red_eta_20_corr.node_strength_[dim_red_eta_20_corr.node_select_]

array([26, 15, 13, 13, 13, 11,  9,  9,  8,  8,  7,  7,  7,  7,  7,  6,  6,
        6,  6,  6])

In [3]:
dim_red_eta_20_atm.node_strength_[dim_red_eta_20_atm.node_select_]

array([14, 14, 13, 12, 12, 12, 11, 11, 11, 10, 10, 10,  9,  9,  9,  8,  8,
        8,  8,  7])

In [4]:
dim_red_eta_50_cov.node_strength_[dim_red_eta_50_cov.node_select_]

array([51, 39, 38, 36, 34, 34, 33, 33, 33, 33, 32, 32, 32, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 30, 29, 28, 28, 28, 28, 27, 27, 27, 26, 26, 26,
       26, 26, 25, 25, 25, 25, 25, 25, 24, 24, 24, 23, 22, 22, 22, 21])

In [6]:
ROI_AAL_list = np.array([ 'Rectus_L','Olfactory_L','Frontal_Sup_Orb_L','Frontal_Med_Orb_L','Frontal_Mid_Orb_L',
                'Frontal_Inf_Orb_L','Frontal_Sup_L','Frontal_Mid_L','Frontal_Inf_Oper_L','Frontal_Inf_Tri_L',
                'Frontal_Sup_Medial_L','Supp_Motor_Area_L','Paracentral_Lobule_L','Precentral_L','Rolandic_Oper_L',
                'Postcentral_L','Parietal_Sup_L','Parietal_Inf_L','SupraMarginal_L','Angular_L','Precuneus_L',
                'Occipital_Sup_L','Occipital_Mid_L','Occipital_Inf_L','Calcarine_L','Cuneus_L','Lingual_L',
                'Fusiform_L','Heschl_L','Temporal_Sup_L','Temporal_Mid_L','Temporal_Inf_L','Temporal_Pole_Sup_L',
                'Temporal_Pole_Mid_L','ParaHippocampal_L','Cingulum_Ant_L','Cingulum_Mid_L','Cingulum_Post_L',
                'Insula_L','Rectus_R','Olfactory_R','Frontal_Sup_Orb_R','Frontal_Med_Orb_R','Frontal_Mid_Orb_R',
                'Frontal_Inf_Orb_R','Frontal_Sup_R','Frontal_Mid_R','Frontal_Inf_Oper_R','Frontal_Inf_Tri_R',
                'Frontal_Sup_Medial_R','Supp_Motor_Area_R','Paracentral_Lobule_R','Precentral_R','Rolandic_Oper_R',
                'Postcentral_R','Parietal_Sup_R','Parietal_Inf_R', 'SupraMarginal_R','Angular_R','Precuneus_R',
                'Occipital_Sup_R','Occipital_Mid_R','Occipital_Inf_R','Calcarine_R','Cuneus_R','Lingual_R',
                'Fusiform_R','Heschl_R','Temporal_Sup_R','Temporal_Mid_R','Temporal_Inf_R','Temporal_Pole_Sup_R',
                'Temporal_Pole_Mid_R','ParaHippocampal_R','Cingulum_Ant_R','Cingulum_Mid_R','Cingulum_Post_R',
                'Insula_R','Hippocampus_L','Hippocampus_R','Amygdala_L','Amygdala_R','Caudate_L','Caudate_R',
                'Putamen_L','Putamen_R','Pallidum_L','Pallidum_R','Thalamus_L','Thalamus_R','Cerebelum_Crus1_L',
                'Cerebelum_Crus1_R','Cerebelum_Crus2_L','Cerebelum_Crus2_R','Cerebelum_3_L','Cerebelum_3_R',
                'Cerebelum_4_5_L','Cerebelum_4_5_R','Cerebelum_6_L','Cerebelum_6_R','Cerebelum_7b_L','Cerebelum_7b_R',
                'Cerebelum_8_L','Cerebelum_8_R','Cerebelum_9_L','Cerebelum_9_R','Cerebelum_10_L','Cerebelum_10_R',
                'Vermis_1_2','Vermis_3','Vermis_4_5','Vermis_6','Vermis_7','Vermis_8','Vermis_9','Vermis_10'])

In [7]:
ROI_AAL_list[dim_red_eta_20_corr.node_select_]

array(['Insula_R', 'Heschl_R', 'Precuneus_L', 'Insula_L',
       'Parietal_Inf_R', 'Parietal_Inf_L', 'Supp_Motor_Area_R',
       'Paracentral_Lobule_R', 'Paracentral_Lobule_L', 'Occipital_Inf_R',
       'Supp_Motor_Area_L', 'Frontal_Sup_L', 'Cingulum_Mid_R',
       'ParaHippocampal_R', 'Postcentral_R', 'Frontal_Sup_R',
       'Cingulum_Mid_L', 'SupraMarginal_L', 'Frontal_Mid_L', 'Lingual_R'],
      dtype='<U20')

In [8]:
ROI_AAL_list[dim_red_eta_20_atm.node_select_]

array(['Parietal_Inf_R', 'Cingulum_Mid_L', 'SupraMarginal_R', 'Insula_L',
       'Calcarine_R', 'Cuneus_R', 'Frontal_Sup_Medial_R', 'Postcentral_L',
       'Rolandic_Oper_L', 'Postcentral_R', 'Cuneus_L', 'Precentral_R',
       'Supp_Motor_Area_L', 'Frontal_Sup_L', 'Lingual_R', 'Olfactory_L',
       'Precuneus_R', 'Frontal_Med_Orb_R', 'Parietal_Inf_L',
       'Paracentral_Lobule_R'], dtype='<U20')

In [9]:
ROI_AAL_list[dim_red_eta_50_cov.node_select_]

array(['Insula_R', 'Supp_Motor_Area_L', 'ParaHippocampal_R',
       'Paracentral_Lobule_R', 'Temporal_Pole_Mid_L', 'Lingual_L',
       'Occipital_Inf_R', 'Supp_Motor_Area_R', 'Fusiform_L',
       'Rolandic_Oper_L', 'Cingulum_Mid_L', 'Heschl_R',
       'Temporal_Pole_Mid_R', 'SupraMarginal_L', 'Frontal_Inf_Orb_R',
       'Cingulum_Post_L', 'ParaHippocampal_L', 'Postcentral_L',
       'Frontal_Inf_Orb_L', 'Temporal_Pole_Sup_R', 'Frontal_Inf_Oper_L',
       'Paracentral_Lobule_L', 'Calcarine_L', 'Temporal_Inf_L',
       'Frontal_Inf_Tri_L', 'Rectus_R', 'Insula_L', 'Occipital_Inf_L',
       'Frontal_Sup_R', 'Calcarine_R', 'Cingulum_Post_R', 'Frontal_Mid_L',
       'Lingual_R', 'Temporal_Inf_R', 'Precentral_L', 'Olfactory_R',
       'Cuneus_L', 'Parietal_Inf_L', 'Precuneus_L', 'Cingulum_Mid_R',
       'Parietal_Inf_R', 'Olfactory_L', 'Frontal_Mid_Orb_R',
       'Precuneus_R', 'Temporal_Pole_Sup_L', 'Occipital_Sup_L',
       'Occipital_Mid_L', 'Precentral_R', 'Fusiform_R',
       'Frontal_In